
version: '3.0'
services:
  web:
    image: "hewwho/io-lab-docker-ci-public:latest"
    ports:
      - "5000:5000"
    # TODO: image, ports and redis dependency
    depends_on: 
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    volumes: 
      - redis-data:/data
volumes:
  redis-data:
    # TODO: persistence for redis. You need to persist /data directory.